// Conturi demo pre-create pentru testare.
// Se încarcă automat în localStorage la prima vizită pe pagina de login.
// Toate au parola "test" pentru simplitate.

export const SEED_USERS = [
  // ─── 10 CLIENȚI ───
  { tip: "client" as const, numeComplet: "Alin Tilvar",       email: "alin.tilvar@yahoo.com",     telefon: "0721000001", parola: "test", animal: { numeAnimal: "Max",     rasa: "Labrador Retriever", greutate: "28", varsta: "4", alergii: "Fără" } },
  { tip: "client" as const, numeComplet: "Maria Popescu",      email: "maria.popescu@gmail.com",   telefon: "0721000002", parola: "test", animal: { numeAnimal: "Bella",   rasa: "Pudel Toy",          greutate: "6",  varsta: "2", alergii: "Polen" } },
  { tip: "client" as const, numeComplet: "Ion Gheorghe",       email: "ion.gheorghe@gmail.com",    telefon: "0721000003", parola: "test", animal: { numeAnimal: "Charlie", rasa: "Husky Siberian",     greutate: "22", varsta: "5", alergii: "Fără" } },
  { tip: "client" as const, numeComplet: "Andrei Dumitrescu",  email: "andrei.dumitrescu@yahoo.com", telefon: "0721000004", parola: "test", animal: { numeAnimal: "Luna",    rasa: "Bichon Maltez",      greutate: "4",  varsta: "3", alergii: "Pui" } },
  { tip: "client" as const, numeComplet: "Elena Popa",         email: "elena.popa@gmail.com",      telefon: "0721000005", parola: "test", animal: { numeAnimal: "Rocky",   rasa: "Ciobănesc German",   greutate: "35", varsta: "6", alergii: "Fără" } },
  { tip: "client" as const, numeComplet: "Cristian Stănescu",  email: "cristian.stanescu@yahoo.com", telefon: "0721000006", parola: "test", animal: { numeAnimal: "Coco",    rasa: "Pisică Persană",     greutate: "5",  varsta: "4", alergii: "Pește" } },
  { tip: "client" as const, numeComplet: "Ioana Munteanu",     email: "ioana.munteanu@gmail.com",  telefon: "0721000007", parola: "test", animal: { numeAnimal: "Milo",    rasa: "Golden Retriever",   greutate: "30", varsta: "2", alergii: "Fără" } },
  { tip: "client" as const, numeComplet: "Răzvan Petrescu",    email: "razvan.petrescu@gmail.com", telefon: "0721000008", parola: "test", animal: { numeAnimal: "Daisy",   rasa: "Yorkshire Terrier",  greutate: "3",  varsta: "5", alergii: "Fără" } },
  { tip: "client" as const, numeComplet: "Diana Constantin",   email: "diana.constantin@yahoo.com", telefon: "0721000009", parola: "test", animal: { numeAnimal: "Simba",   rasa: "Pisică British",     greutate: "6",  varsta: "3", alergii: "Lactate" } },
  { tip: "client" as const, numeComplet: "Mihai Stoica",       email: "mihai.stoica@gmail.com",    telefon: "0721000010", parola: "test", animal: { numeAnimal: "Buddy",   rasa: "Beagle",             greutate: "12", varsta: "4", alergii: "Fără" } },

  // ─── 10 SALOANE ───
  { tip: "salon" as const, numeComplet: "Andrei Pop",       numeSalon: "Paws & Style",         email: "paws@calyhub.test",        telefon: "0731000001", parola: "test", salon: { dateFirma: { numeSalon: "Paws & Style",         adresa: "Str. Florilor 12",  oras: "București", telefon: "0731000001", descriere: "Salon premium cu 10 ani experiență" }, servicii: [{ nume: "Tuns complet", pret: "80", durata: "60" }, { nume: "Băiță", pret: "50", durata: "40" }], echipa: [{ nume: "Maria Ionescu", specialitate: "Rase mici" }] } },
  { tip: "salon" as const, numeComplet: "Mihaela Iancu",    numeSalon: "Fluffy Salon",         email: "fluffy@calyhub.test",      telefon: "0731000002", parola: "test", salon: { dateFirma: { numeSalon: "Fluffy Salon",         adresa: "B-dul Eroilor 24",  oras: "Cluj-Napoca", telefon: "0731000002", descriere: "Styling profesional pentru toate rasele" }, servicii: [{ nume: "Styling complet", pret: "150", durata: "120" }], echipa: [{ nume: "Ana Stan", specialitate: "Toate rasele" }] } },
  { tip: "salon" as const, numeComplet: "Cristina Marin",   numeSalon: "Happy Pets Grooming",  email: "happy@calyhub.test",       telefon: "0731000003", parola: "test", salon: { dateFirma: { numeSalon: "Happy Pets Grooming",  adresa: "Str. Lalelelor 8",  oras: "Timișoara", telefon: "0731000003", descriere: "Grooming relaxant într-un mediu prietenos" }, servicii: [{ nume: "Tuns + Băiță", pret: "120", durata: "90" }], echipa: [{ nume: "Elena Vasile", specialitate: "Rase mari" }] } },
  { tip: "salon" as const, numeComplet: "Ștefan Dobre",     numeSalon: "Royal Dog Salon",      email: "royal@calyhub.test",       telefon: "0731000004", parola: "test", salon: { dateFirma: { numeSalon: "Royal Dog Salon",      adresa: "Calea Mărăței 45",  oras: "Iași", telefon: "0731000004", descriere: "Premium grooming și spa pentru câini" }, servicii: [{ nume: "Premium grooming", pret: "200", durata: "150" }, { nume: "Spa", pret: "100", durata: "60" }], echipa: [{ nume: "Adriana Toma", specialitate: "Premium" }] } },
  { tip: "salon" as const, numeComplet: "Alex Radu",        numeSalon: "Salon Câini Centru",   email: "centru@calyhub.test",      telefon: "0731000005", parola: "test", salon: { dateFirma: { numeSalon: "Salon Câini Centru",   adresa: "Str. Mihai Bravu 100", oras: "București", telefon: "0731000005", descriere: "Salon central, prețuri accesibile" }, servicii: [{ nume: "Tuns rapid", pret: "60", durata: "45" }], echipa: [{ nume: "Bogdan Stan", specialitate: "Tuns rapid" }] } },
  { tip: "salon" as const, numeComplet: "Bianca Voicu",     numeSalon: "Pet Style Premium",    email: "petstyle@calyhub.test",    telefon: "0731000006", parola: "test", salon: { dateFirma: { numeSalon: "Pet Style Premium",    adresa: "Str. Republicii 12", oras: "Brașov", telefon: "0731000006", descriere: "Stil premium pentru animăluțul tău" }, servicii: [{ nume: "Tuns artistic", pret: "180", durata: "120" }], echipa: [{ nume: "Florin Ionescu", specialitate: "Tuns artistic" }] } },
  { tip: "salon" as const, numeComplet: "Daniel Toma",      numeSalon: "Grooming Express",     email: "express@calyhub.test",     telefon: "0731000007", parola: "test", salon: { dateFirma: { numeSalon: "Grooming Express",     adresa: "B-dul Tomis 200",   oras: "Constanța", telefon: "0731000007", descriere: "Grooming rapid, fără programări lungi" }, servicii: [{ nume: "Băiță express", pret: "40", durata: "25" }], echipa: [{ nume: "Camelia Pop", specialitate: "Băiță" }] } },
  { tip: "salon" as const, numeComplet: "Adina Lazăr",      numeSalon: "Cuddly Pets",          email: "cuddly@calyhub.test",      telefon: "0731000008", parola: "test", salon: { dateFirma: { numeSalon: "Cuddly Pets",          adresa: "Str. Cetății 30",   oras: "Sibiu", telefon: "0731000008", descriere: "Grijă cu suflet pentru blănoșii tăi" }, servicii: [{ nume: "Tuns + masaj", pret: "140", durata: "100" }], echipa: [{ nume: "Iulia Moldovan", specialitate: "Wellness" }] } },
  { tip: "salon" as const, numeComplet: "Florin Mocanu",    numeSalon: "Doggy Spa",            email: "doggyspa@calyhub.test",    telefon: "0731000009", parola: "test", salon: { dateFirma: { numeSalon: "Doggy Spa",            adresa: "Str. Aviatorilor 7", oras: "București", telefon: "0731000009", descriere: "Spa luxos pentru câini" }, servicii: [{ nume: "Spa complet", pret: "250", durata: "180" }], echipa: [{ nume: "Roxana Diaconu", specialitate: "Spa" }] } },
  { tip: "salon" as const, numeComplet: "Roxana Neagu",     numeSalon: "CatchDog Grooming",    email: "catchdog@calyhub.test",    telefon: "0731000010", parola: "test", salon: { dateFirma: { numeSalon: "CatchDog Grooming",    adresa: "Str. Trivale 22",   oras: "Pitești", telefon: "0731000010", descriere: "Grooming local pentru câini și pisici" }, servicii: [{ nume: "Tuns standard", pret: "70", durata: "50" }], echipa: [{ nume: "Andreea Vlad", specialitate: "Câini și pisici" }] } },
];
